import { Container } from "@material-ui/core";
import Head from "next/head";
import React from "react";

const Layout: React.FC = ({ children }) => {
  return (
    <>
      <Head>
        <title>Smart KotKot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>

      <Container maxWidth={"lg"}>{children}</Container>
    </>
  );
};

export default Layout;
